<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
        <WasmMainJSPath>AppBundle\main.js</WasmMainJSPath>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SelfContained>false</SelfContained>
        <PublishSingleFile>false</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <WasmExtraFilesToDeploy Include="AppBundle\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Leaquid.App\Leaquid.App.csproj"/>
    </ItemGroup>
</Project>
