<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PublishTrimmed>false</PublishTrimmed>
        <PublishAot>false</PublishAot>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)"/>
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Leaquid.Core\Leaquid.Core.csproj"/>
        <ProjectReference Include="..\Leaquid.UserInterface\Leaquid.UserInterface.csproj"/>
    </ItemGroup>
</Project>
