name: publish-to-android

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 10406996
      - name: Restore workloads
        run: dotnet workload restore
      - name: Publish package
        run: ./scripts/android_build.sh
        env:
          KEYSTORE: ${{secrets.KEYSTORE}}
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
          SIGNINGKEY_PASSWORD: ${{secrets.SIGNINGKEY_PASSWORD}}
      - name: Upload packages as artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: android-packages
          path: Leaquid.Android/bin/Release/net8.0-android/publish
          retention-days: 0
